#!/usr/bin/env bash
# =============================================================================
# setup_repo.sh – Add gh-ai-pipeline to a single repository
# =============================================================================
# Usage:
#   ./scripts/setup_repo.sh <owner/repo> [--ai openai|anthropic|local] [--model <name>]
#
# Examples:
#   ./scripts/setup_repo.sh SA-Baitham/gpr_diffusion
#   ./scripts/setup_repo.sh SA-Baitham/freqtrade --ai anthropic --model claude-3-opus
#   ./scripts/setup_repo.sh SA-Baitham/gpr_data_pipeline --ai openai --model deepseek-v4-flash-free --auto-merge true
# =============================================================================

set -euo pipefail

REPO="${1:?Usage: $0 <owner/repo>}"
AI_PROVIDER="${2:-openai}"
AI_MODEL="${3:-deepseek-v4-flash-free}"
AI_ENDPOINT="${4:-https://opencode.ai/zen/v1}"
AUTO_MERGE="${5:-false}"

WORKFLOW_DIR=".github/workflows"
WORKFLOW_FILE="$WORKFLOW_DIR/ai-pipeline.yml"

echo "🚀 Setting up gh-ai-pipeline for $REPO ..."

# Create a temporary directory
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Clone the repo (just the .github directory)
echo "📦 Cloning $REPO ..."
git clone --depth 1 "https://github.com/$REPO.git" "$TMP_DIR/repo" 2>/dev/null || {
    echo "❌ Failed to clone $REPO. Check the URL and your permissions."
    exit 1
}

cd "$TMP_DIR/repo"

# Ensure .github/workflows exists
mkdir -p "$WORKFLOW_DIR"

# Check if workflow already exists
if [ -f "$WORKFLOW_FILE" ]; then
    echo "⚠️  Workflow already exists at $WORKFLOW_FILE"
    read -p "Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "⏭️  Skipping $REPO"
        exit 0
    fi
fi

# Generate the workflow file
cat > "$WORKFLOW_FILE" << EOF
# Auto-generated by gh-ai-pipeline/setup_repo.sh
name: AI Pipeline

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-pipeline:
    uses: SA-Baitham/gh-ai-pipeline/.github/workflows/ai-pipeline.yml@main
    with:
      ai_provider: $AI_PROVIDER
      ai_model: $AI_MODEL
      ai_endpoint: $AI_ENDPOINT
      auto_merge: $AUTO_MERGE
      auto_merge_method: squash
      review_style: normal
    secrets:
      AI_API_KEY: \\\${{ secrets.AI_API_KEY }}
EOF

echo "✅ Workflow created at $WORKFLOW_FILE"

# Commit and push
git add "$WORKFLOW_FILE"
git commit -m "chore: add AI Pipeline workflow" --no-gpg-sign 2>/dev/null || {
    echo "⏭️  Nothing to commit (already up to date)"
    exit 0
}

echo "📤 Pushing to $REPO ..."
git push origin HEAD 2>/dev/null || {
    echo "❌ Push failed. You may need to push manually:"
    echo "   cd $TMP_DIR/repo && git push origin HEAD"
    exit 1
}

echo ""
echo "✅ Done! $REPO now has the AI Pipeline."
echo ""
echo "Next steps:"
echo "  1. Go to https://github.com/$REPO/settings/secrets/actions"
echo "  2. Add AI_API_KEY (your OpenAI/Anthropic API key)"
echo "  3. Push a branch to test it!"
